spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/woj_new
    username: root
    password: 2w0x0y40706
  data:
    redis:
      host: localhost
      port: 6379
      password: root@123456
      jedis:
        pool:
          min-idle: 10 #连接池中的最小空闲连接
          max-idle: 50 #连接池中的最大空闲连接
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-wait: 2000 #连接池最大阻塞等待时间（使用负值表示没有限制）



server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段
      logic-delete-field: isDelete
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false

springdoc:
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn
  documents:
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/*


emailUtil:
  hostName: smtp.qq.com
  Charset: "UTF-8"
  account: 3153917921@qq.com
  password: unijbjmgvfspdddb
  name: AcKing
# spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug



